name: Cargo Check (Linux)

on:
  pull_request:
    branches: [ main ]

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update && rustup default stable
      - name: Run cargo check
        run: cargo check
        env:
          RUSTFLAGS: -D warnings